spring.application.name=Assignment-8

spring.datasource.url=jdbc:postgresql://localhost:5432/diyazturganaliev
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driverClassName=org.postgresql.Driver

server.port=8888

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=oop
spring.datasource.hikari.auto-commit=false
spring.jpa.show-sql=true